<?php
    function hello_menu() {
        $items = array();
        $items['user_success'] = array(
            'title' => 'New User',
            'page callback' => 'user_function',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function hello_user_insert() {
        $_GET['destination'] = 'user_success';
    }

    function user_function() {
        return '<p>You made a new user! felix navidad</p>';
    }
